// frontend/src/components/JobDetail.tsx
import React, { useEffect, useMemo, useState } from "react";
import { deleteJob, fetchJob, updateJobAnnotation } from "../api";
import type { Job, JobAnnotation, JobAnnotationPriority, JobAnnotationStatus, ParsedPayload } from "../types";

interface JobDetailProps {
  job: Job | null;
  onDeleted: () => void;
  onAnnotationSaved: () => void;
}

const defaultAnnotation: JobAnnotation = {
  status: "unreviewed",
  priority: "medium",
  notes: "",
  why_interesting: "",
  skill_gaps: [],
  follow_up_date: null,
  resume_version: "",
  created_at: null,
  updated_at: null,
};

const annotationStatuses: JobAnnotationStatus[] = [
  "unreviewed",
  "interesting",
  "applied",
  "interviewing",
  "offer",
  "rejected",
  "archived",
];
const annotationPriorities: JobAnnotationPriority[] = ["high", "medium", "low"];

const normalizeAnnotation = (annotation?: JobAnnotation | null): JobAnnotation => ({
  ...defaultAnnotation,
  ...(annotation || {}),
  skill_gaps: annotation?.skill_gaps || [],
});

const JobDetail: React.FC<JobDetailProps> = ({ job, onDeleted, onAnnotationSaved }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [details, setDetails] = useState<Job | null>(null);
  const [parsed, setParsed] = useState<ParsedPayload | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [savingAnnotation, setSavingAnnotation] = useState(false);
  const [annotation, setAnnotation] = useState<JobAnnotation>(defaultAnnotation);
  const [skillGapInput, setSkillGapInput] = useState("");

  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      if (!job) {
        setDetails(null);
        setParsed(null);
        setAnnotation(defaultAnnotation);
        setSkillGapInput("");
        return;
      }
      setLoading(true);
      setError(null);
      try {
        const fullJob = await fetchJob(job.job_id);
        if (cancelled) return;
        setDetails(fullJob);
        setParsed((fullJob.parsed_description?.payload as ParsedPayload) || null);
        const nextAnnotation = normalizeAnnotation(fullJob.annotation);
        setAnnotation(nextAnnotation);
        setSkillGapInput(nextAnnotation.skill_gaps.join(", "));
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load job.");
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };

    load();
    return () => {
      cancelled = true;
    };
  }, [job?.job_id]);

  const formatDate = (value?: string | null) => {
    if (!value) return "n/a";
    return new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value));
  };

  const formatDateTime = (value?: string | null) => {
    if (!value) return "Not saved yet";
    return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
  };

  const formatLabel = (value?: string | null) => {
    if (!value) return "unspecified";
    return value.replace(/_/g, " ");
  };

  const salaryText = (range?: { min?: number | null; max?: number | null }) => {
    if (!range) return "unspecified";
    const { min, max } = range;
    if (min && max) return `${min.toLocaleString()} – ${max.toLocaleString()}`;
    if (min) return `${min.toLocaleString()}+`;
    if (max) return `up to ${max.toLocaleString()}`;
    return "unspecified";
  };

  const benefitsText = (benefits?: string | string[]) => {
    if (!benefits) return "unspecified";
    if (Array.isArray(benefits)) return benefits.length ? benefits.join(", ") : "unspecified";
    return benefits;
  };

  const annotationUpdatedAt = useMemo(() => formatDateTime(annotation.updated_at), [annotation.updated_at]);

  const confirmDelete = async () => {
    if (!details || deleting) return;
    const ok = window.confirm("Delete this job? This cannot be undone.");
    if (!ok) return;
    setDeleting(true);
    try {
      await deleteJob(details.job_id);
      setDetails(null);
      setParsed(null);
      setAnnotation(defaultAnnotation);
      setSkillGapInput("");
      onDeleted();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete job.");
    } finally {
      setDeleting(false);
    }
  };

  const saveAnnotation = async () => {
    if (!details || savingAnnotation) return;
    setSavingAnnotation(true);
    setError(null);
    try {
      const saved = await updateJobAnnotation(details.job_id, {
        ...annotation,
        notes: annotation.notes.trim(),
        why_interesting: annotation.why_interesting.trim(),
        skill_gaps: skillGapInput
          .split(",")
          .map((item) => item.trim())
          .filter(Boolean),
        follow_up_date: annotation.follow_up_date || null,
        resume_version: annotation.resume_version.trim(),
      });
      setAnnotation(normalizeAnnotation(saved));
      setSkillGapInput((saved.skill_gaps || []).join(", "));
      setDetails((current) => (current ? { ...current, annotation: saved } : current));
      onAnnotationSaved();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save annotation.");
    } finally {
      setSavingAnnotation(false);
    }
  };

  return (
    <div className="panel detail-pane">
      <p className="label">Details</p>
      {!job && <div>Select a job to see details.</div>}

      {job && (
        <div className="card">
          <header>
            <div>
              <p className="company">{job.company}</p>
              <h3>{job.title}</h3>
              <p className="muted">
                {job.location} • {job.source}
              </p>
            </div>
            <div className="header-actions">
              {job.url && (
                <a className="link" href={job.url} target="_blank" rel="noreferrer">
                  Open posting
                </a>
              )}
              <button className="danger" type="button" onClick={confirmDelete} disabled={deleting}>
                Delete
              </button>
            </div>
          </header>

          {error && <div className="error">{error}</div>}
          {!error && loading && <div className="muted">Loading details…</div>}
          {!error && !loading && details && (
            <>
              <p className="muted">Scraped {formatDate(details.scraped_at)}</p>

              <details className="annotation-card">
                <summary className="annotation-header annotation-toggle">
                  <div>
                    <p className="summary-title">Personal notes</p>
                    <p className="muted small">Track your own pipeline, fit, and follow-up plan for this job.</p>
                  </div>
                  <div className="annotation-summary-meta">
                    <span className="muted tiny">Last saved: {annotationUpdatedAt}</span>
                    <span className="muted tiny">
                      {formatLabel(annotation.status)} · {formatLabel(annotation.priority)}
                    </span>
                  </div>
                </summary>

                <div className="annotation-grid">
                  <label>
                    <span>Status</span>
                    <select
                      value={annotation.status}
                      onChange={(e) =>
                        setAnnotation((current) => ({
                          ...current,
                          status: e.target.value as JobAnnotationStatus,
                        }))
                      }
                    >
                      {annotationStatuses.map((status) => (
                        <option key={status} value={status}>
                          {formatLabel(status)}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label>
                    <span>Priority</span>
                    <select
                      value={annotation.priority}
                      onChange={(e) =>
                        setAnnotation((current) => ({
                          ...current,
                          priority: e.target.value as JobAnnotationPriority,
                        }))
                      }
                    >
                      {annotationPriorities.map((priority) => (
                        <option key={priority} value={priority}>
                          {formatLabel(priority)}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label>
                    <span>Follow up</span>
                    <input
                      type="date"
                      value={annotation.follow_up_date || ""}
                      onChange={(e) =>
                        setAnnotation((current) => ({
                          ...current,
                          follow_up_date: e.target.value || null,
                        }))
                      }
                    />
                  </label>
                  <label>
                    <span>Resume version</span>
                    <input
                      type="text"
                      placeholder="e.g. ai-general-v2"
                      value={annotation.resume_version}
                      onChange={(e) =>
                        setAnnotation((current) => ({
                          ...current,
                          resume_version: e.target.value,
                        }))
                      }
                    />
                  </label>
                </div>

                <label className="annotation-field">
                  <span>Why interesting</span>
                  <textarea
                    rows={3}
                    placeholder="Why this role is worth your attention."
                    value={annotation.why_interesting}
                    onChange={(e) =>
                      setAnnotation((current) => ({
                        ...current,
                        why_interesting: e.target.value,
                      }))
                    }
                  />
                </label>

                <label className="annotation-field">
                  <span>Skill gaps</span>
                  <input
                    type="text"
                    placeholder="rag, deployment, experimentation"
                    value={skillGapInput}
                    onChange={(e) => setSkillGapInput(e.target.value)}
                  />
                  <span className="muted tiny">Comma-separated. Use this to surface repeated gaps across jobs.</span>
                </label>

                <label className="annotation-field">
                  <span>Notes</span>
                  <textarea
                    rows={5}
                    placeholder="Application angle, interview prep ideas, companies to revisit, etc."
                    value={annotation.notes}
                    onChange={(e) =>
                      setAnnotation((current) => ({
                        ...current,
                        notes: e.target.value,
                      }))
                    }
                  />
                </label>

                <div className="annotation-actions">
                  <button className="primary" type="button" onClick={saveAnnotation} disabled={savingAnnotation}>
                    {savingAnnotation ? "Saving…" : "Save notes"}
                  </button>
                  <span className="muted small">
                    Status: {formatLabel(annotation.status)} · Priority: {formatLabel(annotation.priority)}
                  </span>
                </div>
              </details>

              {parsed && (
                <div className="parsed">
                  <div className="pill-row">
                    <span className="pill">{parsed.seniority || "unspecified"}</span>
                    <span className="pill">{parsed.employment_type || "unspecified"}</span>
                    <span className="pill">{parsed.remote || "unspecified"}</span>
                    <span className="pill">{parsed.location?.[0] || job.location}</span>
                  </div>

                  <div className="summary">
                    <p className="summary-title">Summary</p>
                    {parsed.summary ? <p className="body">{parsed.summary}</p> : <p className="muted">No parsed summary yet.</p>}
                  </div>

                  <div className="grid">
                    <div>
                      <p className="summary-title">Languages</p>
                      <div className="chip-row">
                        {(parsed.languages || []).map((lang) => (
                          <span key={lang} className="chip">
                            {lang}
                          </span>
                        ))}
                        {(!parsed.languages || !parsed.languages.length) && <span className="muted small">n/a</span>}
                      </div>
                    </div>
                    <div>
                      <p className="summary-title">Programming</p>
                      <div className="chip-row">
                        {(parsed.programming_languages || []).map((lang) => (
                          <span key={lang} className="chip">
                            {lang}
                          </span>
                        ))}
                        {(!parsed.programming_languages || !parsed.programming_languages.length) && (
                          <span className="muted small">n/a</span>
                        )}
                      </div>
                    </div>
                    <div>
                      <p className="summary-title">Tools</p>
                      <div className="chip-row">
                        {(parsed.tools || []).map((tool) => (
                          <span key={tool} className="chip">
                            {tool}
                          </span>
                        ))}
                        {(!parsed.tools || !parsed.tools.length) && <span className="muted small">n/a</span>}
                      </div>
                    </div>
                    <div>
                      <p className="summary-title">Skills</p>
                      <div className="chip-row">
                        {(parsed.skills || []).map((skill) => (
                          <span key={skill} className="chip">
                            {skill}
                          </span>
                        ))}
                        {(!parsed.skills || !parsed.skills.length) && <span className="muted small">n/a</span>}
                      </div>
                    </div>
                  </div>

                  <div className="meta">
                    <div>
                      <p className="summary-title">Degree</p>
                      <p className="muted">
                        {parsed.degree_field || "unspecified"} • {parsed.degree_type || "unspecified"}
                      </p>
                    </div>
                    <div>
                      <p className="summary-title">Experience</p>
                      <p className="muted">{parsed.years_experience_min ?? "unspecified"}+ years</p>
                    </div>
                    <div>
                      <p className="summary-title">Salary (EUR)</p>
                      <p className="muted">{salaryText(parsed.salary_eur_range)}</p>
                    </div>
                    <div>
                      <p className="summary-title">Benefits</p>
                      <p className="muted">{benefitsText(parsed["extra benefits"])}</p>
                    </div>
                  </div>
                </div>
              )}

              {details.description ? (
                <details className="raw">
                  <summary>Full description</summary>
                  <p className="body">{details.description}</p>
                </details>
              ) : (
                <p className="muted">No description stored.</p>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default JobDetail;

// frontend/src/components/JobDetail.vue
<template>
  <div class="panel detail-pane">
    <p class="label">Details</p>
    <div v-if="!job">Select a job to see details.</div>

    <div v-else class="card">
      <header>
        <div>
          <p class="company">{{ job.company }}</p>
          <h3>{{ job.title }}</h3>
          <p class="muted">{{ job.location }} • {{ job.source }}</p>
        </div>
        <div class="header-actions">
          <a v-if="job.url" class="link" :href="job.url" target="_blank" rel="noreferrer">Open posting</a>
          <button class="danger" type="button" @click="confirmDelete" :disabled="deleting">Delete</button>
        </div>
      </header>

      <div v-if="error" class="error">{{ error }}</div>
      <div v-else-if="loading" class="muted">Loading details…</div>
      <div v-else-if="details">
        <p class="muted">Scraped {{ formatDate(details.scraped_at) }}</p>

        <div v-if="parsed" class="parsed">
          <div class="pill-row">
            <span class="pill">{{ parsed.seniority || "unspecified" }}</span>
            <span class="pill">{{ parsed.employment_type || "unspecified" }}</span>
            <span class="pill">{{ parsed.remote || "unspecified" }}</span>
            <span class="pill">{{ parsed.location?.[0] || job.location }}</span>
          </div>

          <div class="summary">
            <p class="summary-title">Summary</p>
            <p class="body" v-if="parsed.summary">{{ parsed.summary }}</p>
            <p class="muted" v-else>No parsed summary yet.</p>
          </div>

          <div class="grid">
            <div>
              <p class="summary-title">Languages</p>
              <div class="chip-row">
                <span v-for="lang in parsed.languages || []" :key="lang" class="chip">{{ lang }}</span>
                <span v-if="!parsed.languages || !parsed.languages.length" class="muted small">n/a</span>
              </div>
            </div>
            <div>
              <p class="summary-title">Programming</p>
              <div class="chip-row">
                <span v-for="lang in parsed.programming_languages || []" :key="lang" class="chip">{{ lang }}</span>
                <span v-if="!parsed.programming_languages || !parsed.programming_languages.length" class="muted small">n/a</span>
              </div>
            </div>
            <div>
              <p class="summary-title">Tools</p>
              <div class="chip-row">
                <span v-for="tool in parsed.tools || []" :key="tool" class="chip">{{ tool }}</span>
                <span v-if="!parsed.tools || !parsed.tools.length" class="muted small">n/a</span>
              </div>
            </div>
            <div>
              <p class="summary-title">Skills</p>
              <div class="chip-row">
                <span v-for="skill in parsed.skills || []" :key="skill" class="chip">{{ skill }}</span>
                <span v-if="!parsed.skills || !parsed.skills.length" class="muted small">n/a</span>
              </div>
            </div>
          </div>

          <div class="meta">
            <div>
              <p class="summary-title">Degree</p>
              <p class="muted">{{ parsed.degree_field || "unspecified" }} • {{ parsed.degree_type || "unspecified" }}</p>
            </div>
            <div>
              <p class="summary-title">Experience</p>
              <p class="muted">{{ parsed.years_experience_min ?? "unspecified" }}+ years</p>
            </div>
            <div>
              <p class="summary-title">Salary (EUR)</p>
              <p class="muted">{{ salaryText(parsed.salary_eur_range) }}</p>
            </div>
            <div>
              <p class="summary-title">Benefits</p>
              <p class="muted">{{ benefitsText(parsed["extra benefits"]) }}</p>
            </div>
          </div>
        </div>

        <details class="raw" v-if="details.description">
          <summary>Full description</summary>
          <p class="body">{{ details.description }}</p>
        </details>
        <p v-else class="muted">No description stored.</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { deleteJob, fetchJob } from "../api";
import type { Job, ParsedPayload } from "../types";

const props = defineProps<{
  job: Job | null;
}>();

const emit = defineEmits<{ (e: "deleted"): void }>();

const loading = ref(false);
const error = ref<string | null>(null);
const details = ref<Job | null>(null);
const parsed = ref<ParsedPayload | null>(null);
const deleting = ref(false);

const load = async () => {
  if (!props.job) {
    details.value = null;
    parsed.value = null;
    return;
  }
  loading.value = true;
  error.value = null;
  try {
    details.value = await fetchJob(props.job.job_id);
    parsed.value = (details.value?.parsed_description?.payload as ParsedPayload) || null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to load job.";
  } finally {
    loading.value = false;
  }
};

const formatDate = (value?: string) => {
  if (!value) return "n/a";
  return new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value));
};

const confirmDelete = async () => {
  if (!details.value || deleting.value) return;
  const ok = window.confirm("Delete this job? This cannot be undone.");
  if (!ok) return;
  deleting.value = true;
  try {
    await deleteJob(details.value.job_id);
    details.value = null;
    parsed.value = null;
    emit("deleted");
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to delete job.";
  } finally {
    deleting.value = false;
  }
};

const salaryText = (range?: { min?: number | null; max?: number | null }) => {
  if (!range) return "unspecified";
  const { min, max } = range;
  if (min && max) return `${min.toLocaleString()} – ${max.toLocaleString()}`;
  if (min) return `${min.toLocaleString()}+`;
  if (max) return `up to ${max.toLocaleString()}`;
  return "unspecified";
};

const benefitsText = (benefits?: string | string[]) => {
  if (!benefits) return "unspecified";
  if (Array.isArray(benefits)) return benefits.length ? benefits.join(", ") : "unspecified";
  return benefits;
};

watch(
  () => props.job?.job_id,
  () => load(),
  { immediate: true }
);

onMounted(load);
</script>

<style scoped>
.detail-pane {
  display: flex;
  flex-direction: column;
  gap: 10px;
  min-height: 420px;
}

.card {
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 14px;
  background: #f8fafc;
}

header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 8px;
}

.header-actions {
  display: flex;
  gap: 8px;
  align-items: center;
}

.company {
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 12px;
  margin: 0 0 2px;
  color: var(--muted);
}

h3 {
  margin: 0 0 2px;
}

.detail-pane .muted {
  margin: 0;
}

.body {
  white-space: pre-wrap;
  line-height: 1.6;
}

.parsed {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin: 10px 0;
}

.pill-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.pill {
  padding: 6px 10px;
  border-radius: 999px;
  background: #e2e8f0;
  font-weight: 700;
  text-transform: capitalize;
}

.summary {
  background: #fff;
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 10px 12px;
}

.summary-title {
  margin: 0 0 4px;
  font-weight: 700;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 10px;
}

.chip-row {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.chip {
  background: #0f172a;
  color: #e2e8f0;
  padding: 4px 8px;
  border-radius: 10px;
  font-size: 12px;
}

.meta {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 8px;
}

.raw {
  border: 1px dashed var(--border);
  border-radius: 12px;
  padding: 8px 10px;
  background: #fff;
}

.link {
  color: #0ea5e9;
  font-weight: 700;
}

.danger {
  background: #fee2e2;
  color: #b91c1c;
  border: 1px solid #fecaca;
  border-radius: 10px;
  padding: 8px 10px;
  font-weight: 700;
  cursor: pointer;
}

.detail-pane .label {
  margin: 0 0 6px;
  display: inline-block;
}

.error {
  color: #b91c1c;
  background: #fef2f2;
  border: 1px solid #fecaca;
  padding: 10px 12px;
  border-radius: 10px;
}

@media (max-width: 960px) {
  header {
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>
