// frontend/src/components/RecentRuns.vue
<template>
  <section class="panel">
    <div class="header">
      <div>
        <p class="label">Recent runs</p>
        <h3>Latest activity</h3>
      </div>
      <button class="ghost" type="button" @click="load" :disabled="loading">Refresh</button>
    </div>

    <div v-if="error" class="error">{{ error }}</div>
    <div v-else-if="loading" class="muted">Loading…</div>
    <div v-else-if="!runs.length" class="muted">No runs yet.</div>
    <div v-else class="list">
      <div v-for="run in runs" :key="run.run_id" class="row">
        <div class="top">
          <span class="pill small mode" :class="modeClass(run.mode)">{{ modeLabel(run.mode) }}</span>
          <span class="pill small" :class="run.status">{{ run.status }}</span>
        </div>
        <p class="muted small">{{ formatDate(run.started_at) }}</p>
        <p class="muted tiny">{{ run.run_id.slice(0, 10) }}</p>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { listRuns } from "../api";
import type { CliMode, RunSummary } from "../types";

const runs = ref<RunSummary[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);

const load = async () => {
  loading.value = true;
  error.value = null;
  try {
    runs.value = await listRuns(5);
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to load runs.";
  } finally {
    loading.value = false;
  }
};

const modeLabel = (mode: CliMode) => {
  switch (mode) {
    case "run-once":
      return "Run";
    case "reset-ai-purge":
      return "Reset AI purge";
    case "parse-descriptions":
      return "Parse descriptions";
    case "db-summary":
      return "DB summary";
    case "test":
      return "Test";
    case "purge":
      return "Purge (rules + AI)";
    default:
      return mode;
  }
};

const modeClass = (mode: CliMode) => `mode-${mode.replace(/[^a-z]/g, "-")}`;

const formatDate = (value?: string | null) => {
  if (!value) return "n/a";
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
};

onMounted(load);

defineExpose({ reload: load });
</script>

<style scoped>
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-bottom: 6px;
}

.list {
  display: grid;
  gap: 8px;
}

.row {
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 10px;
  background: #fff;
}

.row p {
  margin: 0;
}

.top {
  display: flex;
  gap: 6px;
  align-items: center;
  margin-bottom: 4px;
}

.pill.mode {
  border: none;
}

.pill.mode-run-once {
  background: #eef2ff;
  color: #4338ca;
}

.pill.mode-purge {
  background: #fff1f2;
  color: #be123c;
}

.pill.mode-reset-ai-purge {
  background: #f1f5f9;
  color: #0f172a;
}

.pill.mode-parse-descriptions {
  background: #ecfeff;
  color: #0ea5e9;
}

.pill.mode-db-summary {
  background: #fff7ed;
  color: #b45309;
}

.pill.mode-test {
  background: #f3e8ff;
  color: #7c3aed;
}

.pill.running {
  background: #ecfeff;
  color: #0284c7;
}

.pill.succeeded {
  background: #ecfdf3;
  color: #15803d;
}

.pill.failed {
  background: #fef2f2;
  color: #b91c1c;
}

.error {
  color: #b91c1c;
  background: #fef2f2;
  border: 1px solid #fecaca;
  padding: 10px;
  border-radius: 10px;
  font-weight: 600;
}
</style>

// frontend/src/components/RecentRuns.tsx
import React, { useEffect, useState } from "react";
import { listRuns } from "../api";
import type { CliMode, RunSummary } from "../types";

interface RecentRunsProps {
  className?: string;
}

const modeLabel = (mode: CliMode) => {
  switch (mode) {
    case "run-once":
      return "Run";
    case "reset-ai-purge":
      return "Reset AI purge";
    case "parse-descriptions":
      return "Parse descriptions";
    case "db-summary":
      return "DB summary";
    case "test":
      return "Test";
    case "purge":
      return "Purge (rules + AI)";
    default:
      return mode;
  }
};

const modeClass = (mode: CliMode) => `mode-${mode.replace(/[^a-z]/g, "-")}`;

const formatDate = (value?: string | null) => {
  if (!value) return "n/a";
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
};

const RecentRuns: React.FC<RecentRunsProps> = ({ className }) => {
  const [runs, setRuns] = useState<RunSummary[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      setRuns(await listRuns(5));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load runs.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const wrapperClassName = ["panel", "recent-runs", className].filter(Boolean).join(" ");

  return (
    <section className={wrapperClassName}>
      <div className="header">
        <div>
          <p className="label">Recent runs</p>
          <h3>Latest activity</h3>
        </div>
        <button className="ghost" type="button" onClick={load} disabled={loading}>
          Refresh
        </button>
      </div>

      {error ? (
        <div className="error">{error}</div>
      ) : loading ? (
        <div className="muted">Loading…</div>
      ) : !runs.length ? (
        <div className="muted">No runs yet.</div>
      ) : (
        <div className="list">
          {runs.map((run) => (
            <div key={run.run_id} className="row">
              <div className="top">
                <span className={`pill small mode ${modeClass(run.mode)}`}>{modeLabel(run.mode)}</span>
                <span className={`pill small ${run.status}`}>{run.status}</span>
              </div>
              <p className="muted small">{formatDate(run.started_at)}</p>
              <p className="muted tiny">{run.run_id.slice(0, 10)}</p>
            </div>
          ))}
        </div>
      )}
    </section>
  );
};

export default RecentRuns;
